"""Canonical names for the built-in MCP tool catalog."""

from __future__ import annotations

BUILTIN_TOOL_NAMES = frozenset(
    {
        "get_nodes",
        "get_node_status",
        "get_vms",
        "get_vm_config",
        "set_vm_description",
        "create_vm",
        "clone_vm",
        "execute_vm_command",
        "start_vm",
        "stop_vm",
        "shutdown_vm",
        "reset_vm",
        "delete_vm",
        "get_storage",
        "get_cluster_status",
        "list_jobs",
        "get_job",
        "poll_job",
        "cancel_job",
        "retry_job",
        "get_containers",
        "start_container",
        "stop_container",
        "restart_container",
        "update_container_resources",
        "create_container",
        "delete_container",
        "execute_container_command",
        "update_container_ssh_keys",
        "get_container_config",
        "set_container_description",
        "get_container_ip",
        "list_snapshots",
        "create_snapshot",
        "delete_snapshot",
        "rollback_snapshot",
        "list_isos",
        "list_templates",
        "download_iso",
        "delete_iso",
        "list_backups",
        "create_backup",
        "restore_backup",
        "delete_backup",
        "get_node_syslog",
        "get_task_log",
        "get_cluster_log",
        "get_node_firewall_log",
        "get_guest_firewall_log",
    }
)
